2020/08/26 16:33:13 [info] 26#26 discovery started
2020/08/26 16:33:13 [notice] 26#26 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/26 16:33:13 [info] 1#1 controller started
2020/08/26 16:33:13 [notice] 1#1 process 26 exited with code 0
2020/08/26 16:33:13 [info] 28#28 router started
2020/08/26 16:33:13 [info] 28#28 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/26 16:33:13 [info] 29#29 "django-app" application started
2020/08/26 16:42:57 [info] 17#17 discovery started
2020/08/26 16:42:57 [notice] 17#17 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/26 16:42:57 [info] 1#1 controller started
2020/08/26 16:42:57 [notice] 1#1 process 17 exited with code 0
2020/08/26 16:42:57 [info] 19#19 router started
2020/08/26 16:42:57 [info] 19#19 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/26 16:42:57 [info] 20#20 "django-app" application started
2020/08/26 20:58:38 [info] 16#16 discovery started
2020/08/26 20:58:38 [notice] 16#16 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/26 20:58:38 [info] 1#1 controller started
2020/08/26 20:58:38 [notice] 1#1 process 16 exited with code 0
2020/08/26 20:58:38 [info] 18#18 router started
2020/08/26 20:58:38 [info] 18#18 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/26 20:58:38 [info] 19#19 "django-app" application started
2020/08/26 22:49:36 [info] 16#16 discovery started
2020/08/26 22:49:36 [notice] 16#16 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/26 22:49:36 [info] 1#1 controller started
2020/08/26 22:49:36 [notice] 1#1 process 16 exited with code 0
2020/08/26 22:49:36 [info] 18#18 router started
2020/08/26 22:49:36 [info] 18#18 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/26 22:49:36 [info] 19#19 "django-app" application started
2020/08/26 22:51:29 [notice] 1#1 process 17 exited with code 0
2020/08/26 22:51:29 [notice] 1#1 process 18 exited with code 0
2020/08/26 22:51:30 [notice] 1#1 process 19 exited with code 0
2020/08/27 11:00:35 [info] 16#16 discovery started
2020/08/27 11:00:35 [notice] 16#16 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 11:00:35 [info] 1#1 controller started
2020/08/27 11:00:35 [notice] 1#1 process 16 exited with code 0
2020/08/27 11:00:35 [info] 18#18 router started
2020/08/27 11:00:35 [info] 18#18 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 11:00:35 [info] 19#19 "django-app" application started
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/sessions/backends/base.py", line 199, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/sites.py", line 249, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/sites.py", line 220, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/sites.py", line 194, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 224, in inner
    self._setup()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 360, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/__init__.py", line 173, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/__init__.py", line 58, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/sessions/backends/base.py", line 64, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/sessions/backends/base.py", line 204, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1137, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
2020/08/27 11:16:49 [notice] 1#1 process 17 exited with code 0
2020/08/27 11:16:49 [notice] 1#1 process 18 exited with code 0
2020/08/27 11:16:49 [notice] 1#1 process 19 exited with code 0
2020/08/27 16:14:42 [info] 23#23 discovery started
2020/08/27 16:14:42 [notice] 23#23 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:14:42 [info] 22#22 controller started
2020/08/27 16:14:42 [notice] 22#22 process 23 exited with code 0
2020/08/27 16:14:42 [info] 26#26 router started
2020/08/27 16:14:42 [info] 26#26 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:14:42 [info] 30#30 "django-app" application started
2020/08/27 16:14:42 [alert] 30#30 Python failed to import module "bikehub.wsgi"
Traceback (most recent call last):
  File "/code/bikehub/bikehub/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'corsheaders'
2020/08/27 16:14:43 [notice] 22#22 process 30 exited with code 1
2020/08/27 16:14:43 [warn] 26#26 failed to start application "django-app"
2020/08/27 16:14:43 [alert] 26#26 failed to apply new conf
2020/08/27 16:14:44 [info] 17#17 discovery started
2020/08/27 16:14:44 [notice] 17#17 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:14:44 [info] 1#1 controller started
2020/08/27 16:14:44 [notice] 1#1 process 17 exited with code 0
2020/08/27 16:14:44 [info] 19#19 router started
2020/08/27 16:14:44 [info] 19#19 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:15:55 [notice] 1#1 process 18 exited with code 0
2020/08/27 16:15:55 [notice] 1#1 process 19 exited with code 0
2020/08/27 16:20:25 [info] 20#20 discovery started
2020/08/27 16:20:25 [notice] 20#20 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:20:25 [info] 19#19 controller started
2020/08/27 16:20:25 [notice] 19#19 process 20 exited with code 0
2020/08/27 16:20:25 [info] 23#23 router started
2020/08/27 16:20:25 [info] 23#23 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:20:25 [info] 27#27 "django-app" application started
2020/08/27 16:20:25 [alert] 27#27 Python failed to import module "bikehub.wsgi"
Traceback (most recent call last):
  File "/code/bikehub/bikehub/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'corsheaders'
2020/08/27 16:20:26 [notice] 19#19 process 27 exited with code 1
2020/08/27 16:20:26 [warn] 23#23 failed to start application "django-app"
2020/08/27 16:20:26 [alert] 23#23 failed to apply new conf
2020/08/27 16:20:26 [info] 17#17 discovery started
2020/08/27 16:20:26 [notice] 17#17 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:20:26 [info] 1#1 controller started
2020/08/27 16:20:26 [notice] 1#1 process 17 exited with code 0
2020/08/27 16:20:26 [info] 19#19 router started
2020/08/27 16:20:26 [info] 19#19 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:22:00 [notice] 1#1 process 18 exited with code 0
2020/08/27 16:22:00 [notice] 1#1 process 19 exited with code 0
2020/08/27 16:22:09 [info] 26#26 discovery started
2020/08/27 16:22:09 [notice] 26#26 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:22:09 [info] 1#1 controller started
2020/08/27 16:22:09 [notice] 1#1 process 26 exited with code 0
2020/08/27 16:22:09 [info] 28#28 router started
2020/08/27 16:22:09 [info] 28#28 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:22:34 [notice] 1#1 process 27 exited with code 0
2020/08/27 16:22:34 [notice] 1#1 process 28 exited with code 0
2020/08/27 16:22:40 [info] 17#17 discovery started
2020/08/27 16:22:40 [notice] 17#17 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:22:40 [info] 1#1 controller started
2020/08/27 16:22:40 [notice] 1#1 process 17 exited with code 0
2020/08/27 16:22:40 [info] 19#19 router started
2020/08/27 16:22:40 [info] 19#19 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:22:55 [notice] 1#1 process 18 exited with code 0
2020/08/27 16:22:55 [notice] 1#1 process 19 exited with code 0
2020/08/27 16:25:21 [info] 20#20 discovery started
2020/08/27 16:25:21 [notice] 20#20 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:25:21 [info] 19#19 controller started
2020/08/27 16:25:21 [notice] 19#19 process 20 exited with code 0
2020/08/27 16:25:21 [info] 23#23 router started
2020/08/27 16:25:21 [info] 23#23 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:25:21 [info] 27#27 "django-app" application started
2020/08/27 16:25:22 [notice] 19#19 process 22 exited with code 0
2020/08/27 16:25:22 [notice] 19#19 process 23 exited with code 0
2020/08/27 16:25:22 [notice] 19#19 process 27 exited with code 0
2020/08/27 16:25:22 [info] 38#38 discovery started
2020/08/27 16:25:22 [notice] 38#38 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 16:25:22 [info] 1#1 controller started
2020/08/27 16:25:22 [notice] 1#1 process 38 exited with code 0
2020/08/27 16:25:22 [info] 40#40 router started
2020/08/27 16:25:22 [info] 40#40 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 16:25:22 [info] 41#41 "django-app" application started
2020/08/27 16:26:52 [notice] 1#1 process 39 exited with code 0
2020/08/27 16:26:52 [notice] 1#1 process 40 exited with code 0
2020/08/27 16:26:52 [notice] 1#1 process 41 exited with code 0
2020/08/27 17:01:37 [info] 21#21 discovery started
2020/08/27 17:01:37 [notice] 21#21 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:01:37 [info] 20#20 controller started
2020/08/27 17:01:37 [notice] 20#20 process 21 exited with code 0
2020/08/27 17:01:37 [info] 24#24 router started
2020/08/27 17:01:37 [info] 24#24 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:01:37 [info] 28#28 "django-app" application started
2020/08/27 17:01:38 [notice] 20#20 process 23 exited with code 0
2020/08/27 17:01:38 [notice] 20#20 process 24 exited with code 0
2020/08/27 17:01:38 [notice] 20#20 process 28 exited with code 0
2020/08/27 17:01:38 [info] 40#40 discovery started
2020/08/27 17:01:38 [notice] 40#40 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:01:38 [info] 1#1 controller started
2020/08/27 17:01:38 [notice] 1#1 process 40 exited with code 0
2020/08/27 17:01:38 [info] 42#42 router started
2020/08/27 17:01:38 [info] 42#42 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:01:38 [info] 43#43 "django-app" application started
Invalid HTTP_HOST header: 'example'. You may need to add 'example' to ALLOWED_HOSTS.
Bad Request: /
2020/08/27 17:04:12 [notice] 1#1 process 41 exited with code 0
2020/08/27 17:04:12 [notice] 1#1 process 42 exited with code 0
2020/08/27 17:04:12 [notice] 1#1 process 43 exited with code 0
2020/08/27 17:04:21 [info] 16#16 discovery started
2020/08/27 17:04:21 [notice] 16#16 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:04:21 [info] 1#1 controller started
2020/08/27 17:04:21 [notice] 1#1 process 16 exited with code 0
2020/08/27 17:04:21 [info] 18#18 router started
2020/08/27 17:04:21 [info] 18#18 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:04:21 [info] 19#19 "django-app" application started
2020/08/27 17:04:37 [notice] 1#1 process 17 exited with code 0
2020/08/27 17:04:38 [notice] 1#1 process 18 exited with code 0
2020/08/27 17:04:38 [notice] 1#1 process 19 exited with code 0
2020/08/27 17:04:56 [info] 17#17 discovery started
2020/08/27 17:04:56 [notice] 17#17 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:04:56 [info] 1#1 controller started
2020/08/27 17:04:56 [notice] 1#1 process 17 exited with code 0
2020/08/27 17:04:56 [info] 19#19 router started
2020/08/27 17:04:56 [info] 19#19 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:04:56 [info] 20#20 "django-app" application started
2020/08/27 17:05:27 [notice] 1#1 process 18 exited with code 0
2020/08/27 17:05:27 [notice] 1#1 process 19 exited with code 0
2020/08/27 17:05:27 [notice] 1#1 process 20 exited with code 0
2020/08/27 17:12:28 [info] 21#21 discovery started
2020/08/27 17:12:28 [notice] 21#21 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:12:28 [info] 20#20 controller started
2020/08/27 17:12:28 [notice] 20#20 process 21 exited with code 0
2020/08/27 17:12:28 [info] 24#24 router started
2020/08/27 17:12:28 [info] 24#24 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:12:28 [info] 28#28 "django-app" application started
2020/08/27 17:12:29 [notice] 20#20 process 23 exited with code 0
2020/08/27 17:12:29 [notice] 20#20 process 24 exited with code 0
2020/08/27 17:12:29 [notice] 20#20 process 28 exited with code 0
2020/08/27 17:12:29 [info] 39#39 discovery started
2020/08/27 17:12:29 [notice] 39#39 module: python 3.7.3 "/usr/lib/unit/modules/python3.7.unit.so"
2020/08/27 17:12:29 [info] 1#1 controller started
2020/08/27 17:12:29 [notice] 1#1 process 39 exited with code 0
2020/08/27 17:12:29 [info] 41#41 router started
2020/08/27 17:12:29 [info] 41#41 OpenSSL 1.1.1d  10 Sep 2019, 1010104f
2020/08/27 17:12:29 [info] 42#42 "django-app" application started
